<div>
    @include('content.partials.toolbar')
    @include('content.partials.kanban')
    @include('content.partials.table')
    @include('content.partials.calendar')
    @include('content.partials.modals.create-edit')
    @include('content.partials.modals.approve')
    @include('content.partials.modals.tiktok-qc')
    @include('content.partials.modals.delete')
</div>
